set -g prefix C-Space

set -g mouse on
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*:Tc"
set -ga terminal-features ",*:hyperlinks"
set -g allow-passthrough on
set -g status-position top
set -g base-index 1
set -g renumber-windows on
setw -g mode-keys vi
set -g allow-rename off
setw -g automatic-rename off
